project:
  type: website

website:
  page-navigation: true
  title: "STA 542 Fall 2025"
  description: "Homepage for STA 542 Introduction to Time Series Analysis at Duke University, Fall 2025."
  site-url: "https://sta542-f25.github.io/"

  #repo-url: https://github.com/sta240-s25/sta240-s25.github.io/
  #repo-actions: [edit, issue]

  open-graph: true

#  draft-mode: unlinked

  sidebar:
    background: "#DAF7A6"
    logo: "img/logo.png"
    pinned: true
    align: center
#    tools:
#      - icon: github
#        href: https://github.com/sta199-s25
#        text: "GitHub organization"
#      - icon: code-square
#        href: https://cmgr.oit.duke.edu/containers
#        text: "RStudio containers"
#      - icon: life-preserver
#        text: Support
#        menu:
#          - icon: person-raised-hand
#            text: Office hours
#            href: https://docs.google.com/spreadsheets/d/1gXNQ9UMT01bU9qr-YDsA2GIpslldHmfwPg1gcOj2GTA/edit?usp=sharing
#          - icon: people-fill
#            text: Help from humans (Ed Discussion)
#            href: https://edstem.org/us/courses/62468/discussion/
#          - icon: robot
#            text: Help from AI (Chatbot)
#            href: https://canvas.duke.edu/courses/39994/external_tools/5887
#      - icon: file-check-fill
#        text: "Canvas"
#        menu:
#          - icon: megaphone-fill
#            text: Announcements
#            url: https://canvas.duke.edu/courses/39994/announcements
#          - icon: file-arrow-up-fill
#            text: Gradescope
#            url: https://canvas.duke.edu/courses/39994/external_tools/181
#          - icon: alphabet-uppercase
#            text: Gradebook
#            url: https://canvas.duke.edu/courses/39994/gradebook

    style: docked
    search: true
    collapse-level: 1
    contents:
      - section: "Syllabus"
        contents:
          - href: syllabus/syllabus_overview.qmd
            text: Overview
          - href: syllabus/syllabus_assignments.qmd
            text: Assignments and grading
          - href: syllabus/syllabus_policies.qmd
            text: Policies
          - href: index.qmd
            text: Schedule
      - section: "Problem Sets"
        contents:
          - href: psets/pset-0.qmd
            text: Problem Set 0
          - href: psets/pset-1.qmd
            text: Probem Set 1
            
  page-footer:
    right: 'This page is built with [Quarto](https://quarto.org/).'
    left: "&copy; Copyright 2025 John Zito"
    background: "#DAF7A6"

format: 
  html:
    mainfont: Atkinson Hyperlegible
    highlight-style: a11y-light

theme:
  light: [cosmo, style/sta199.scss]
#  dark: [cosmo, style/sta199.scss, style/dark.scss]
linkcolor: "#798b93"
toc: true
code-copy: hover
code-link: true
code-overflow: wrap

execute:
  freeze: auto

editor: visual