project:
  type: website

website:
  page-navigation: true
  title: "STA 542 Fall 2025"
  description: "Homepage for STA 542 Introduction to Time Series Analysis at Duke University, Fall 2025."
  site-url: "https://sta542-f25.github.io/"

  open-graph: true

#  draft-mode: unlinked

  sidebar:
    background: "#DAF7A6"
    logo: "img/logo.png"
    pinned: true
    align: center

    style: docked
    search: true
    collapse-level: 1
    contents:
      - href: syllabus/syllabus.qmd
        text: Syllabus
      #- section: "Background"
      #- section: "Lecture notes"
      #  contents:
      #    - href: lecture-notes/ar-1.qmd
      #      text: All about the AR(1)
      #- section: "R Explainers"
      - section: "Problem Sets"
        contents:
          - href: problems/pset-0.qmd
            text: Problem Set 0
          - href: problems/pset-1.qmd
            text: Probem Set 1
            
  page-footer:
    right: 'This page is built with [Quarto](https://quarto.org/).'
    left: "&copy; Copyright 2025 John Zito"
    background: "#DAF7A6"

format: 
  html:
    mainfont: Atkinson Hyperlegible
    highlight-style: a11y-light

theme:
  light: [cosmo, style/sta199.scss]
#  dark: [cosmo, style/sta199.scss, style/dark.scss]
linkcolor: "#798b93"
toc: true
code-copy: hover
code-link: true
code-overflow: wrap

execute:
  freeze: auto