---
title: "University resources"
---

## Course costs

If you are having difficulty with the costs associated with this course (obtaining a laptop, mostly), here are some resources:

-   [**Karsh Office of Undergraduate Support**](https://financialaid.duke.edu/)**:** Regardless of your aid package, Karsh offers loans and resources for connecting students with campus programs that might help alleviate course costs.

-   [**DukeLIFE**](https://dukelife.duke.edu/programs/course-materials-assistance/)**:** The Course Material Assistance program offers assistance for eligible students, including through the [LIFE Loaner Laptop Program](https://dukelife.duke.edu/academic-support/loaner-laptop-program/). Students who are eligible for DukeLIFE benefits are notified before the start of the semester; program resources are limited.

-   [**Duke Link**](https://link.duke.edu/)**:** They have a small supply of laptops that can be rented out for five days at a time.

## Tech support

Contact the Duke OIT Service Desk at [oit.duke.edu/help](https://oit.duke.edu/help).

## Academic support

There are times you may need help with the class that is beyond what can be provided by the teaching team. In those instances, I encourage you to visit the Academic Resource Center. The [Academic Resource Center (ARC)](https://arc.duke.edu) offers free services to all students during their undergraduate careers at Duke. Services include Learning Consultations, Peer Tutoring and Study Groups, ADHD/LD Coaching, Outreach Workshops, and more. Because learning is a process unique to every individual, they work with each student to discover and develop their own academic strategy for success at Duke. Contact the ARC to schedule an appointment. Undergraduates in any year, studying any discipline can benefit! Contact [ARC\@duke.edu](mailto:arc@duke.edu), 919-684-5917.

## Accessibility

If any portion of the course is not accessible to you due to challenges with technology or the course format, please let me know so we can make appropriate accommodations.

The [Student Disability Access Office (SDAO)](https://access.duke.edu/students) is available to ensure that students can engage with their courses and related assignments. Students should contact the SDAO to [request or update accommodations](https://access.duke.edu/requests) under these circumstances.

## Mental health and well-being

Duke is committed to holistic student well-being, including mental, emotional, and physical health. The university offers resources to help students manage daily stress, encourage intentional self-care, and access just-in-time support. If you find you need support, your mental and/or emotional health concerns are impacting your day-to-day activities and your academic performance, or you need someone to talk to, the resources below are available to you:

-   [**DukeReach**](https://students.duke.edu/wellness/dukereach/)**:** DukeReach provides comprehensive outreach services to support students in managing all aspects of well-being, including referrals and follow-up services for students who are experiencing significant challenges related to mental health, physical health, social adjustment, and/or a variety of other stressors. You can reach the DukeReach team at [dukereach\@duke.edu](mailto:dukereach@duke.edu).
-   [**Counseling and Psychological Services (CAPS)**](https://students.duke.edu/wellness/caps/)**:** CAPS services include individual and group counseling services, psychiatric services, and workshops. CAPS also provides referrals to off-campus resources for specialized care. You can reach CAPS at (919) 660-1000.
-   [**TimelyCare**](https://Timelycare.com/bluedevils)**:** TimelyCare is an online platform that is a convenient, confidential, and free way for Duke students to receive 24/7 mental health support through TalkNow and scheduled counseling.
-   [**BC Fellows for Healthy Relationship**](https://students.duke.edu/wellness/duwell/sexualhealth/balthrop-cassidy-fellowship/)**:** The BC Fellows meet with students individually and in groups, supporting the development of healthy relationships and building meaningful community in all areas of a student’s life.
-   [**DukeLine**](https://sites.duke.edu/dukeline/)**:** Students who want to connect anonymously with a Peer Coach can text 984-230-4888 from 5 to 11 p.m. daily. DukeLine offers in-the-moment anonymous, non-emergency text support from a peer.
-   [**DuWell**](https://students.duke.edu/wellness/duwell/)**:** DuWell provides Moments of Mindfulness (stress management and resilience building) and meditation programming (Koru workshop) to assist students in developing a daily emotional well-being practice. All are welcome, and no experience is necessary. You can reach DuWell at (919) 681-8421.
