---
title: "Course materials"
---

## Textbooks

The course does not have a designated textbook, and you are not required to purchase anything, but here are several you should know about:

- `[SS]` *Time Series Analysis and Its Applications, 5e* by Robert Shumway and David Stoffer ([free pdf](https://doi.org/10.1007/978-3-031-70584-7));
- `[Skä]` *Bayesian Filtering and Smoothing, 1e* by Simo Särkkä ([free pdf](https://users.aalto.fi/~ssarkka/pub/cup_book_online_20131111.pdf));
- `[WH]` *Bayesian Forecasting and Dynamic Models, 2e* by Mike West and Jeff Harrison ([free pdf](https://doi.org/10.1007/b98971));
- `[PPC]` *Dynamic Linear Models with `R`* by Giovanni Petris, Sonia Petrone, and Patrizia Campagnoli ([free pdf](https://doi.org/10.1007/b135794));
- `[HA]` *Forecasting: Principles and Practice, 3e* by Rob Hyndman and George Athanasopoulos ([online edition](https://otexts.com/fpp3/));
- `[PFW]` *Time Series: Modeling, Computation, and Inference, 2e* by Raquel Prado, Marco Ferreira, and Mike West;
- `[Ham]` *Time Series Analysis* by James Hamilton;
- `[DK]` *Time Series Analysis by State Space Methods, 2e* by James Durbin and Siem Jan Koopman.


I will list readings in the **PREPARE** column of the [course schedule](https://sta542-f25.github.io/).

## Technology

Lecture will largely be a low tech affair: pencil and paper should be sufficient most of the time. You should plan to bring a laptop or tablet device to lab. In general, you will need access to a device with internet so that you can use the following:

-   [This course page](https://sta240-s25.github.io/) that you are on right now;
-   `R`/`RStudio` via the [Duke Container Manager](https://cmgr.oit.duke.edu/containers);
-   [Canvas](https://go.canvas.duke.edu/), through which you can access...
    -   [Gradescope](https://www.gradescope.com/courses/944220);
    -   [Ed Discussion](https://edstem.org/us/courses/71371/discussion);
-   [Zoom](https://duke.zoom.us/) (e.g. for remote office hours).

If access to technology becomes a concern for you during the semester, contact the instructor immediately to discuss options.
