---
title: "Problem Set 1"
subtitle: Due Friday September 19 at 5PM
editor: 
  mode: source
---

- derive non-stationary AR(1) covariance kernel
- do recursive and joint simulations many times and verify that you get the same sample moments;
- invert a Toeplitz matrix;
- Bayesian AR(1) with a funky prior;
- explore frequentist properties of OLS when shit is non-stationary;
- Work backwords from the joint to the recursion;
- efficient bayesian regression recursions when the data are streaming;
- some aymptotics 
- forecasting with real data
- Pierre Jacob?
- fuck with the prior to make the prior predictive look how you want it to

1. covariance kernel
2. here's a process you haven't seen. derive joint. is it stationary?
3. dependent data asymptotics
4. simulate 
5. mle
6. bayes
7. forecasting
8.  real data analysis
9.  general AR(p) shit
10. general AR(p) shit

## Problem 1

{{< include bank/autoregression/covariance-kernel.qmd >}}

## Problem 2

## Problem 3

## Problem 4

## Problem 5

## Problem 6

{{< include bank/autoregression/streaming-conjugate-bayes.qmd >}}

## Problem 7

## Problem 8

## Problem 9

## Problem 10

## Submission

{{< include bank/_submission.qmd >}}